"""The documentation must describe the program that actually exists.

Hand-written flag tables rot silently: an option is added, the page is not
touched, and the site confidently documents something else. These tests read the
CLI's real signatures and check the published pages against them.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
MKDOCS = REPO / "mkdocs.yml"

COMMANDS = ("search", "probe", "assess", "scan", "download", "extract", "run", "benchmark")

#: Options every command inherits. They are documented once, in a shared table,
#: rather than repeated under all eight commands.
SHARED_FLAGS = frozenset(
    {"--config", "--failure-log", "--verbose", "--quiet", "--help", "-v", "-q"}
)


def flags_of(command: str) -> set[str]:
    """Every long option the command actually declares.

    Read from Click's parameter objects, not from rendered ``--help``. Rich
    truncates long option names in its output -- ``--no-check-files`` becomes
    ``--no-check-fil...`` -- by an amount that varies with the Rich version, so
    a test that parsed the rendering passed locally and failed on CI.
    """
    import typer.main

    from gwaspoker.cli import app

    subcommand = typer.main.get_command(app).commands[command]
    names = {
        opt
        for param in subcommand.params
        for opt in (*param.opts, *param.secondary_opts)
        if opt.startswith("--")
    }
    return names - SHARED_FLAGS


@pytest.fixture(scope="module")
def cli_reference() -> str:
    path = DOCS / "cli-reference.md"
    assert path.exists(), "run `python docs/generate_cli_reference.py`"
    return path.read_text(encoding="utf-8")


# ======================================================================
# The site is complete and internally consistent
# ======================================================================


def test_every_nav_page_exists() -> None:
    """A nav entry pointing at a missing file breaks the build."""
    nav = MKDOCS.read_text(encoding="utf-8")
    pages = re.findall(r":\s*([\w-]+\.md)\s*$", nav, flags=re.MULTILINE)
    assert pages, "no nav pages were parsed out of mkdocs.yml"
    missing = [p for p in pages if not (DOCS / p).exists()]
    assert not missing, f"nav references missing pages: {missing}"


def test_every_docs_page_is_in_the_nav() -> None:
    """An unreferenced page is invisible on the site -- usually a rename left over."""
    nav = MKDOCS.read_text(encoding="utf-8")
    on_disk = {p.name for p in DOCS.glob("*.md")}
    unreferenced = sorted(name for name in on_disk if name not in nav)
    assert not unreferenced, f"pages not reachable from the nav: {unreferenced}"


def test_internal_links_resolve() -> None:
    """A link to a page that no longer exists is a dead end on the site."""
    broken: list[str] = []
    for page in DOCS.glob("*.md"):
        for target in re.findall(
            r"\]\(([\w./-]+\.md)(?:#[\w-]+)?\)", page.read_text(encoding="utf-8")
        ):
            if not (page.parent / target).resolve().exists():
                broken.append(f"{page.name} -> {target}")
    assert not broken, f"broken internal links: {broken}"


# ======================================================================
# The CLI reference matches the CLI
# ======================================================================


def test_every_command_has_a_section(cli_reference: str) -> None:
    missing = [c for c in COMMANDS if f"## `{c}`" not in cli_reference]
    assert not missing, f"commands with no section in cli-reference.md: {missing}"


@pytest.mark.parametrize("command", COMMANDS)
def test_every_flag_is_documented(command: str, cli_reference: str) -> None:
    """The guard that matters: a new option must reach the published page.

    `cli-reference.md` is generated by `docs/generate_cli_reference.py`. If this
    fails, the generator has not been re-run since the CLI changed.
    """
    section = cli_reference.split(f"## `{command}`", 1)[-1].split("\n## ", 1)[0]
    undocumented = sorted(flag for flag in flags_of(command) if f"`{flag}`" not in section)
    assert not undocumented, (
        f"`{command}` has undocumented flags: {undocumented}. "
        "Re-run: python docs/generate_cli_reference.py"
    )


def test_the_reference_is_current(cli_reference: str) -> None:
    """Regenerating must be a no-op, or the committed page is stale."""
    from gwaspoker import __version__

    assert f"**{__version__}**" in cli_reference, (
        "cli-reference.md was generated for a different version. "
        "Re-run: python docs/generate_cli_reference.py"
    )


# ======================================================================
# Claims made in prose stay true
# ======================================================================


def test_documented_failure_categories_exist() -> None:
    """Every category named in failures.md must be a real enum member."""
    from gwaspoker.failures import FailureCategory

    real = {c.value for c in FailureCategory}
    page = (DOCS / "failures.md").read_text(encoding="utf-8")
    # Anchored to a letter so the exit-code table (`0`, `1`, `2`) is not read
    # as a list of category names.
    named = set(re.findall(r"^\| `([a-z][a-z0-9_]+)` \|", page, flags=re.MULTILINE))
    invented = sorted(named - real)
    assert not invented, f"failures.md names categories that do not exist: {invented}"


def test_every_failure_category_is_documented() -> None:
    from gwaspoker.failures import FailureCategory

    page = (DOCS / "failures.md").read_text(encoding="utf-8")
    missing = sorted(c.value for c in FailureCategory if f"`{c.value}`" not in page)
    assert not missing, f"undocumented failure categories: {missing}"


def test_documented_config_settings_exist() -> None:
    """configuration.md must not describe settings the dataclass does not have."""
    import dataclasses

    from gwaspoker.config import GWASPokerConfig

    real = {f.name for f in dataclasses.fields(GWASPokerConfig)}
    page = (DOCS / "configuration.md").read_text(encoding="utf-8")
    # Anchored to a letter so numeric first cells elsewhere on the page are not
    # read as setting names.
    named = set(re.findall(r"^\| `([a-z][a-z0-9_]+)` \|", page, flags=re.MULTILINE))
    invented = sorted(named - real)
    assert not invented, f"configuration.md names settings that do not exist: {invented}"


def test_published_test_counts_are_true() -> None:
    """Docs state how many tests there are; the number must be the real one.

    A count in prose rots the moment a test is added, and a rotted count in the
    one place a reader checks credibility is worse than no count at all. This
    fails when they diverge, so updating the docs is part of adding a test.
    """
    collected = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "--collect-only"],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=dict(os.environ, PYTHONIOENCODING="utf-8"),
    ).stdout
    match = re.search(r"(\d+)/\d+ tests collected|^(\d+) tests collected", collected, re.MULTILINE)
    assert match, "could not read the collected count from pytest"
    total = match.group(1) or match.group(2)

    for page in ("index.md", "architecture.md", "reproducibility.md"):
        text = (DOCS / page).read_text(encoding="utf-8")
        for stale in re.findall(r"\b(\d{3})\b(?= unit tests| \| none)", text):
            assert stale == total, f"{page} says {stale} tests, pytest collects {total}"
    assert f"<strong>{total}</strong>" in (DOCS / "index.md").read_text(encoding="utf-8")
