"""Self-contained HTML report.

The successor to v1's ``<phenotype>_output.html``. Two differences matter:

* **Self-contained.** v1 linked Bootstrap from a CDN, so the report rendered
  unstyled offline, on an air-gapped cluster, or once that CDN URL changed. The
  CSS here is inlined.
* **Provenance is shown, not implied.** Every extracted count states its source,
  every file selection states its reason, and every byte count is reported.
"""

from __future__ import annotations

import html
from collections.abc import Iterable
from pathlib import Path
from typing import Any, Optional

from gwaspoker.processing.formats import human_size
from gwaspoker.provenance import ProvenanceRecord

_CSS = """
:root{--bg:#ffffff;--fg:#1a1c1f;--muted:#5b6470;--line:#e3e6ea;--accent:#1f5fa9;
--ready:#1a7f47;--partial:#a5720b;--notready:#b3261e;--surface:#f6f8fa;}
@media (prefers-color-scheme: dark){:root{--bg:#14161a;--fg:#e6e9ee;--muted:#9aa4b2;
--line:#2a2f37;--accent:#6ba7e8;--ready:#4cc38a;--partial:#e2b13c;--notready:#f2726a;
--surface:#1b1e24;}}
*{box-sizing:border-box}
body{margin:0;padding:2rem 1.25rem;background:var(--bg);color:var(--fg);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
.wrap{max-width:1140px;margin:0 auto}
h1{font-size:1.7rem;margin:0 0 .25rem;letter-spacing:-.01em}
h2{font-size:1.15rem;margin:2rem 0 .6rem;padding-bottom:.3rem;border-bottom:1px solid var(--line)}
h3{font-size:.95rem;margin:1.2rem 0 .4rem;color:var(--muted);text-transform:uppercase;
letter-spacing:.05em;font-weight:600}
.sub{color:var(--muted);margin:0 0 1.5rem}
.card{background:var(--surface);border:1px solid var(--line);border-radius:8px;
padding:1rem 1.15rem;margin:0 0 1.15rem}
.scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}
table{border-collapse:collapse;width:100%;font-size:.88rem;min-width:520px}
th,td{text-align:left;padding:.45rem .6rem;border-bottom:1px solid var(--line);
vertical-align:top}
th{font-weight:600;color:var(--muted);white-space:nowrap}
td.num{text-align:right;font-variant-numeric:tabular-nums}
code,.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.85em}
.badge{display:inline-block;padding:.12rem .5rem;border-radius:999px;font-size:.78rem;
font-weight:600}
.READY{background:color-mix(in srgb,var(--ready) 16%,transparent);color:var(--ready)}
.PARTIAL{background:color-mix(in srgb,var(--partial) 18%,transparent);color:var(--partial)}
.NOT_READY{background:color-mix(in srgb,var(--notready) 16%,transparent);color:var(--notready)}
.UNKNOWN{background:var(--line);color:var(--muted)}
.unknown{color:var(--muted);font-style:italic}
.ok{color:var(--ready);font-weight:600}
.warn{color:var(--partial);font-weight:600}
.bad{color:var(--notready);font-weight:600}
ul.notes{margin:.4rem 0;padding-left:1.2rem;color:var(--muted);font-size:.88rem}
.kv{display:grid;grid-template-columns:minmax(150px,auto) 1fr;gap:.3rem 1rem;font-size:.9rem}
.kv dt{color:var(--muted)}
.kv dd{margin:0}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--line);
color:var(--muted);font-size:.82rem}
.header-row{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
font-size:.82rem;background:var(--surface);padding:.6rem .75rem;border-radius:6px;
border:1px solid var(--line);overflow-x:auto;white-space:pre}
"""


def _esc(value: Any) -> str:
    """HTML-escape a value, rendering absence explicitly."""
    if value is None or value == "":
        return '<span class="unknown">unknown</span>'
    return html.escape(str(value))


def _bool_cell(value: Optional[bool]) -> str:
    if value is None:
        return '<span class="unknown">unknown</span>'
    return '<span class="ok">yes</span>' if value else '<span class="bad">no</span>'


def _count(value: Optional[int]) -> str:
    if value is None:
        return '<span class="unknown">unknown</span>'
    return f"{value:,}"


def _table(
    headers: Iterable[str], rows: Iterable[Iterable[str]], *, numeric: tuple[int, ...] = ()
) -> str:
    head = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    body = []
    for row in rows:
        cells = "".join(
            f'<td class="num">{cell}</td>' if index in numeric else f"<td>{cell}</td>"
            for index, cell in enumerate(row)
        )
        body.append(f"<tr>{cells}</tr>")
    return (
        '<div class="scroll"><table><thead><tr>'
        + head
        + "</tr></thead><tbody>"
        + "".join(body)
        + "</tbody></table></div>"
    )


def _document(title: str, body: str, provenance: Optional[ProvenanceRecord]) -> str:
    footer = ""
    if provenance is not None:
        env = provenance.environment
        footer = (
            "<footer>Generated by GWASPoker "
            f"{html.escape(env.gwaspoker_version)} on Python "
            f"{html.escape(env.python_version)} at {html.escape(env.timestamp_utc)}."
            + (
                f" GWAS Catalog data release {html.escape(str(env.catalog_data_release))}."
                if env.catalog_data_release
                else ""
            )
            + (f" EFO {html.escape(str(env.efo_version))}." if env.efo_version else "")
            + "</footer>"
        )
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"<title>{html.escape(title)}</title><style>{_CSS}</style></head>"
        f'<body><div class="wrap">{body}{footer}</div></body></html>'
    )


def write_report(
    path: Path,
    *,
    title: str = "GWASPoker report",
    search_results: Optional[list[Any]] = None,
    assessments: Optional[list[Any]] = None,
    provenance: Optional[ProvenanceRecord] = None,
) -> Path:
    """Write a self-contained HTML report."""
    sections: list[str] = [
        f"<h1>{html.escape(title)}</h1>",
        '<p class="sub">API-aware pre-download triage of GWAS summary statistics '
        "for PRS workflows.</p>",
    ]

    if search_results:
        sections.append(_search_section(search_results))
    if assessments:
        sections.append(_assessment_summary_section(assessments))
        for assessment in assessments:
            sections.append(_assessment_detail_section(assessment))

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_document(title, "".join(sections), provenance), encoding="utf-8")
    return path


def _search_section(results: list[Any]) -> str:
    from gwaspoker.metadata.ancestry import summarize_ancestries

    rows = []
    for result in results:
        study = result.study
        samples = study.samples
        rows.append(
            [
                f"<code>{_esc(study.study_accession)}</code>",
                _esc(study.reported_trait),
                _esc(
                    summarize_ancestries([g for a in study.ancestries for g in a.ancestral_groups])
                ),
                _count(samples.total),
                _count(samples.cases),
                _count(samples.controls),
                _bool_cell(study.summary_statistics_available),
                _esc(study.study_year),
                _esc(study.pubmed_id),
            ]
        )
    return (
        "<h2>Study search</h2>"
        + _table(
            ["GCST", "Trait", "Population", "N", "Cases", "Controls", "Sum stats", "Year", "PMID"],
            rows,
            numeric=(3, 4, 5, 7, 8),
        )
        + _provenance_note(results)
    )


def _provenance_note(results: list[Any]) -> str:
    sources: dict[str, int] = {}
    for result in results:
        for source in (
            result.study.samples.total_source.value,
            result.study.samples.cases_source.value,
            result.study.samples.controls_source.value,
        ):
            sources[source] = sources.get(source, 0) + 1
    parts = ", ".join(f"{count} x {name}" for name, count in sorted(sources.items()))
    return f'<ul class="notes"><li>Sample-count provenance across all rows: {html.escape(parts)}.</li></ul>'


def _assessment_summary_section(assessments: list[Any]) -> str:
    rows = []
    for result in assessments:
        study = result.study
        api = result.api_assessment
        readiness = result.readiness
        verdict = readiness.verdict.value if readiness else "UNKNOWN"
        rows.append(
            [
                f"<code>{_esc(study.study_accession if study else result.target)}</code>",
                _esc(study.reported_trait if study else None),
                _esc(api.ssf_metadata.ssf_status if api and api.ssf_metadata else None),
                _bool_cell(api.sufficient_for_prs_assessment if api else None),
                human_size(result.resolved_file.size_bytes if result.resolved_file else None),
                human_size(result.probe.transfer.received_bytes if result.probe else 0),
                f'<span class="badge {verdict}">{verdict}</span>',
            ]
        )
    return "<h2>PRS readiness summary</h2>" + _table(
        ["GCST", "Trait", "SSF status", "API sufficient", "File size", "Bytes probed", "Verdict"],
        rows,
        numeric=(4, 5),
    )


def _assessment_detail_section(result: Any) -> str:
    study = result.study
    api = result.api_assessment
    resolved = result.resolved_file
    probe = result.probe
    readiness = result.readiness
    heading = study.study_accession if study else result.target

    parts = [f"<h2>{html.escape(str(heading))}</h2>", '<div class="card"><dl class="kv">']
    if study is not None:
        parts.append(f"<dt>Reported trait</dt><dd>{_esc(study.reported_trait)}</dd>")
        parts.append(f"<dt>Mapped trait</dt><dd>{_esc(study.mapped_trait_label)}</dd>")
        parts.append(f"<dt>Publication</dt><dd>{_esc(study.publication_title)}</dd>")
        parts.append(f"<dt>PMID</dt><dd>{_esc(study.pubmed_id)}</dd>")
        parts.append(f"<dt>Metadata API</dt><dd><code>{_esc(study.api_source)}</code></dd>")
    if api is not None:
        parts.append(
            "<dt>Structured assessment</dt><dd>"
            + (
                "sufficient — the data file was not read"
                if api.sufficient_for_prs_assessment
                else f"insufficient ({html.escape(api.availability.value)})"
            )
            + f" · {api.bytes_received:,} bytes · {api.latency_seconds:.2f} s</dd>"
        )
        if api.ssf_metadata is not None:
            meta = api.ssf_metadata
            parts.append(f"<dt>Declared format</dt><dd>{_esc(meta.file_type)}</dd>")
            parts.append(f"<dt>Genome build</dt><dd>{_esc(meta.genome_assembly)}</dd>")
    if resolved is not None:
        parts.append(f"<dt>File selected</dt><dd><code>{_esc(resolved.name)}</code></dd>")
        parts.append(f"<dt>Selection reason</dt><dd>{_esc(resolved.selection_reason)}</dd>")
        parts.append(f"<dt>Remote size</dt><dd>{human_size(resolved.size_bytes)}</dd>")
    if probe is not None:
        transfer = probe.transfer
        reduction = (
            f" ({transfer.transfer_reduction * 100:.4f}% of the file not transferred)"
            if transfer.transfer_reduction is not None
            else ""
        )
        parts.append(
            f"<dt>Bytes probed</dt><dd>{human_size(transfer.received_bytes)}{html.escape(reduction)}</dd>"
        )
        parts.append(f"<dt>Encoding</dt><dd>{_esc(probe.encoding)}</dd>")
    parts.append("</dl></div>")

    if probe is not None and probe.header is not None:
        header = probe.header
        parts.append("<h3>Detected header</h3>")
        parts.append(f'<div class="header-row">{html.escape("  ".join(header.raw_header))}</div>')
        parts.append(
            f'<ul class="notes"><li>Row {header.header_row_index}, '
            f"{html.escape(header.delimiter_label)}-separated, "
            f"{header.confidence:.0%} confidence, "
            f"{len(header.preamble_lines)} preamble line(s) skipped.</li></ul>"
        )

    if probe is not None and probe.mapping is not None:
        parts.append("<h3>Canonical mapping</h3>")
        parts.append(
            _table(
                ["#", "Column", "Canonical concept", "PRS", "Method", "Confidence"],
                [
                    [
                        str(index),
                        f"<code>{_esc(column.raw_name)}</code>",
                        (
                            _esc(column.canonical_name)
                            if column.canonical_name != "unknown"
                            else '<span class="unknown">unknown</span>'
                        ),
                        _esc(column.prs_tool_symbol),
                        html.escape(column.mapping_method),
                        f"{column.confidence:.2f}",
                    ]
                    for index, column in enumerate(probe.mapping.columns)
                ],
                numeric=(0, 5),
            )
        )

    if readiness is not None:
        parts.append(_readiness_block(readiness))

    if result.error:
        parts.append(f'<ul class="notes"><li class="bad">{_esc(result.error)}</li></ul>')
    if result.notes:
        parts.append(
            '<ul class="notes">' + "".join(f"<li>{_esc(n)}</li>" for n in result.notes) + "</ul>"
        )
    return "".join(parts)


def _readiness_block(readiness: Any) -> str:
    verdict = readiness.verdict.value
    parts = [
        "<h3>PRS readiness</h3>",
        f'<p><span class="badge {verdict}">{verdict}</span> '
        f'<span class="unknown">evidence: {html.escape(readiness.evidence_source)}</span></p>',
    ]
    rows = [
        [
            html.escape(r.status.symbol),
            html.escape(r.label),
            ", ".join(f"<code>{_esc(c)}</code>" for c in r.satisfied_by) or "—",
            html.escape(r.note or ""),
        ]
        for r in (*readiness.required, *readiness.recommended)
    ]
    parts.append(_table(["", "Field", "Satisfied by", "Note"], rows))
    if readiness.warnings:
        parts.append(
            '<ul class="notes">'
            + "".join(f'<li class="warn">{_esc(w)}</li>' for w in readiness.warnings)
            + "</ul>"
        )
    parts.append(f"<p><strong>Decision:</strong> {_esc(readiness.decision)}</p>")
    return "".join(parts)
